# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: beva/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - apk add --update --no-cache git

test:
  script:
    - hugo mod get -u
    - hugo
  except:
    refs:
      - master

pages:
  script:
    - hugo mod get -u
    - hugo
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
